# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: 'Accessibility Insights Action'
description: 'Task to scan for accessibility issues'
inputs:
    output-dir:
        description: 'Folder containing the scan report.'
        default: '_accessibility-reports'
        required: true
    static-site-dir:
        description: 'Folder containing website content.'
        default: ${{ github.workspace }}
        required: true
    static-site-url-relative-path:
        description: 'Relative path to directory used to construct base scan url. e.g. / on Ubuntu and // on Windows'
        required: true
        default: '/'
    chrome-path:
        description: 'Path to Chrome executable.'
        required: false
    url:
        description: 'The hosted URL to scan/crawl for accessibility issues.'
        required: false
    max-urls:
        description: 'Maximum number of pages opened by crawler. The crawl will stop when this limit is reached.'
        required: false
        default: '100'
    discovery-patterns:
        description: 'List of RegEx patterns to crawl in addition to the provided URL, separated by space.'
        required: false
    input-file:
        description: 'File path that contains list of URLs (each separated by a new line) to scan in addition to URLs discovered from crawling the provided URL.'
        required: false
    input-urls:
        description: 'List of URLs to crawl in addition to URLs discovered from crawling the provided URL, separated by space.'
        required: false
    static-site-port:
        description: 'The preferred local website TCP port to use when scanning local website content.'
        required: false
    scan-timeout:
        description: 'The maximum timeout in milliseconds for the scan (excluding dependency setup)'
        required: false
        default: 90000
    baseline-file:
        description: 'The old baseline file path, a new baseline will be generated with the same name, if null baseline option will be disabled.'
        required: false
    single-worker:
        description: 'To get deterministic scanning results, either specify the singleWorker parameter or ensure that the value specified for the maxUrls parameter is larger than the total number of urls in the web site being scanned.'
        required: true
        default: true
    fail-on-accessibility-error:
        description: 'Fail the build if there are accessibility issues.'
        required: true
        default: true
runs:
    using: 'node16'
    main: 'dist/index.js'
    pre: 'dist/setup.js'
